drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
drop table if exists public.athlete cascade;
drop table if exists public.athlete_medal_search cascade;
create table public.athlete (name_slug varchar(255) not null, bronze_medals_count int4 not null, country_code varchar(255), country_name varchar(255), discipline_name varchar(255), discipline_slug varchar(255), gold_medals_count int4 not null, name varchar(255), participations_count int4 not null, silver_medals_count int4 not null, url varchar(255), primary key (name_slug));
create table public.athlete_medal_search (searched_name_slug varchar(255) not null, primary key (searched_name_slug));
