spring:
  config:
    import: optional:file:env.yaml # Load environment variables

  datasource:
    driver-class-name: org.postgresql.Driver # Will fail when trying to connect to another type of DB.
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?stringtype=unspecified&reWriteBatchedInserts=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: drop-and-create
              drop-target: drop_and_create.sql
              create-target: drop_and_create.sql
              drop-source: metadata
              create-source: metadata
